### PR TITLE
support local app dev via proxy

### PR DESCRIPTION
**Pull request by kevodwyer**
see: https://github.com/Peergos/Peergos/pull/969

### CODE REVIEW

**Review by ianopolous — APPROVED** [review]

**Comment by jonaswre** [comment]
Is there already documentation for this feature?

**Comment by ianopolous** [comment]
There isn't documentation yet, but you need to run peergos with -app-dev-target http://localhost:$PORT
Then log in to localhost with ?local-app-dev=true in the URL query string. Then any app you run will end up getting its assets from your local server instead of peergos. API calls are still handled in the normal way.

**Comment by jonaswre** [comment]
Thanks

**Comment by jonaswre** [comment]
@ianopolous can you provide me with a latest jar? It might be a good Idea to have a workflow for native and for the jar.

And I must say i have trouble running the native packages the only output is 

> Couldn't load native crypto library at , using pure Java version...
To use the native linux-x86-64 crypto implementation use option -Djava.library.path=native-lib
Starting Peergos daemon version: 0.10.0-web-ui/7f871b58c483972eeb50960378b413f407dfc211
Looking up OS: linux
Looking up architecture: amd64

This is for wsl and native windows. The jar is working fine.

**Comment by ianopolous** [comment]
Is there any more if you run natively with -log-to-console true?

**Comment by jonaswre** [comment]
> Couldn't load native crypto library at , using pure Java version...
To use the native linux-x86-64 crypto implementation use option -Djava.library.path=native-lib
Jul 28, 2022 10:37:11 PM peergos.server.util.Logging init
INFO: Logging to /home/jonaswre/.peergos/peergos.0.log
Starting Peergos daemon version: 0.10.0-web-ui/7f871b58c483972eeb50960378b413f407dfc211
Looking up OS: linux
Looking up architecture: amd64
Jul 28, 2022 10:37:11 PM peergos.server.storage.IpfsInstaller ensureInstalled
INFO: ipfs-exe /home/jonaswre/.peergos/ipfs not available
Jul 28, 2022 10:37:11 PM peergos.server.storage.IpfsInstaller install
INFO: Downloading ipfs binary https://github.com/peergos/ipfs-nucleus-releases/blob/main/v0.2.2/linux-amd64/ipfs?raw=true...
Jul 28, 2022 10:37:11 PM peergos.server.util.Logging lambda$init$0
SEVERE: Uncaught Exception in thread 1:main
java.lang.RuntimeException: java.lang.RuntimeException: java.net.MalformedURLException: Accessing an URL protocol that was not enabled. The URL protocol https is supported but not enabled by default. It must be enabled by adding the --enable-url-protocols=https option to the native-image command.
        at peergos.server.Main.startPeergos(Main.java:745)
        at peergos.server.Command.main(Command.java:75)
        at peergos.server.Command.main(Command.java:63)
        at peergos.server.Main.main(Main.java:907)
Caused by: java.lang.RuntimeException: java.net.MalformedURLException: Accessing an URL protocol that was not enabled. The URL protocol https is supported but not enabled by default. It must be enabled by adding the --enable-url-protocols=https option to the native-image command.
        at peergos.server.storage.IpfsInstaller.install(IpfsInstaller.java:308)
        at peergos.server.storage.IpfsInstaller.ensureInstalled(IpfsInstaller.java:255)
        at peergos.server.storage.IpfsInstaller.ensureInstalled(IpfsInstaller.java:168)
        at peergos.server.Main.lambda$static$0(Main.java:71)
        at peergos.server.Command.main(Command.java:75)
        at peergos.server.Main.startPeergos(Main.java:525)
        ... 3 more
Caused by: java.net.MalformedURLException: Accessing an URL protocol that was not enabled. The URL protocol https is supported but not enabled by default. It must be enabled by adding the --enable-url-protocols=https option to the native-image command.
        at com.oracle.svm.core.jdk.JavaNetSubstitutions.unsupported(JavaNetSubstitutions.java:261)
        at com.oracle.svm.core.jdk.JavaNetSubstitutions.getURLStreamHandler(JavaNetSubstitutions.java:235)
        at java.net.URL.getURLStreamHandler(URL.java:81)
        at java.net.URL.<init>(URL.java:680)
        at java.net.URL.fromURI(URL.java:748)
        at java.net.URI.toURL(URI.java:1139)
        at peergos.server.storage.IpfsInstaller.install(IpfsInstaller.java:284)
        ... 8 more

I think I had this error on my main computer.

**Comment by ianopolous** [comment]
Awesome that should be easy to fix.

**Pull request merged**
