### PR TITLE
Refactor upload

### PR DESCRIPTION
**Pull request by kevodwyer**
remove recursive functions

### CODE REVIEW

**Comment by ianopolous** [comment]
Were you able to reproduce the error?

**Comment by ianopolous** [comment]
Does this affect upload and delete?

**Comment by kevodwyer** [comment]
> Were you able to reproduce the error?

no

**Comment by kevodwyer** [comment]
> Does this affect upload and delete?

affects upload only. Delete does not use recursion

**Review by ianopolous — APPROVED** [review]

**Pull request merged**
