### PR TITLE
Make closing sub apps go back in history

### PR DESCRIPTION
**Pull request by ianopolous**

### CODE REVIEW

**Review by kevodwyer — APPROVED** [review]

**Comment by kevodwyer** [comment]
I have done some testing with the new 'close' == back action. I am not convinced it is suitable for the md browser

**Comment by ianopolous** [comment]
What issues did you hit?

**Comment by kevodwyer** [comment]
> What issues did you hit?

If i got from one .md file to another .md file to another .md file i don't expect that clicking close will take me back to the previous .md file and so on just to close the md browser completely.

**Comment by ianopolous** [comment]
Ah, you mean the close in the md browser, not the other apps?

**Comment by ianopolous** [comment]
Yep, that's fair. I've reverted md-browser to going forward in history to drive.

**Review by kevodwyer — APPROVED** [review]

**Pull request merged**
