### PR TITLE
Add packaging into container image

### PR DESCRIPTION
**Pull request by gsaslis**
This adds a first `Containerfile` that can be used to package Peergos into a container image. 

Notes: 

- a multi-stage build is used so that the final container image only contains the JRE + the app (no unnecessary JDK stuff)
- a `Dockerfile` is added as a symbolic link to the vendor-agnostic `Containerfile`, for convenience
- here's a link about "Containerfile vs. Dockerfile" - https://github.com/containers/buildah/discussions/3170
- this PR is still WIP - we should probably still add some github action that builds the container image, runs some smoke test against it and publishes to a container image registry.

### CODE REVIEW

**Review by ianopolous — APPROVED** [review]

**Comment by ianopolous** [comment]
I can't see a way to make it run checks here, so I'll just merge it I think.

**Comment by gsaslis** [comment]
@ianopolous I'd rather we figured out how to run them on the PR before merging to verify it works.

**Comment by ianopolous** [comment]
ok I'll look into it

**Comment by gsaslis** [comment]
@ianopolous how about this: https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks#approving-workflow-runs-on-a-pull-request-from-a-public-fork

**Pull request merged**
